site: Bokeh Front Page

ga_id: "UA-127553611-4"

collections:
  - features
  - goals
  - scenarios
  - users

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
